### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by evabronskayaa** [makivila/my_dota2_stats#1]
Было бы еще неплохо прикрепить ссылку на сайт, где брала эти данные

**Comment by evabronskayaa** [comment]
Не совсем понятно как будешь делать Winrate по героям
У тебя будет несколько индикаторов такого типа или тут будет инфа по самому популярному герою? 

Прошу прощения, ахаха, я за игры не особу шарю, особенно за доту)

**Comment by makivila** [comment]
> Было бы еще неплохо прикрепить ссылку на сайт, где брала эти данные

Добавила

**Comment by makivila** [comment]
> Не совсем понятно как будешь делать Winrate по героям У тебя будет несколько индикаторов такого типа или тут будет инфа по самому популярному герою?
> 
> Прошу прощения, ахаха, я за игры не особу шарю, особенно за доту)

Реализовала карточку героя, где есть возможность выбрать интересующего героя и увидеть winrate по нему и картинку, как этот герой выглядит.
