### ISSUE TITLE
data.py

### ISSUE THREAD

**Issue by evabronskayaa** [makivila/my_dota2_stats#3]
Там на самом деле все нормалёк

У тебя просто в модуле и получение данных, и препроцессинг данных, и процессинг данных.
Я бы наверное чтение и препроцессинг (pd.json_normalize(matches.json())) оставила в одном модуле, а обработку вынесла в другой модуль, но тут на вкус и цвет так сказать

**Comment by evabronskayaa** [comment]
Я только за использование чего-то нового)

Про pd.cut и его параметры я не рассказывала вроде.
Расскажешь что такое?)

**Comment by makivila** [comment]
Данная функция по

> Я только за использование чего-то нового)
> 
> Про pd.cut и его параметры я не рассказывала вроде. Расскажешь что такое?)

Данная функция позволяет разделить данные на категории. Что-то вроде ntile() в sql.
